version: '3.8'
services:
  db:
    image: postgres:15
    container_name: django_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: p09-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

networks:
  django_network:

volumes:
  postgres_data:
