name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - sonarqube-automation
  pull_request:
    branches:
      - main
      - sonarqube-automation

jobs:
  sonarQube:
    runs-on: [self-hosted, windows]

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          fetch-depth: '0'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set SONAR_HOST_URL and SONAR_TOKEN variables
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "SonarQube Scan Starting..."
          sonar-scanner "-Dsonar.projectKey=pingeso-p09" `
                         "-Dsonar.sources=." `
                         "-Dsonar.host.url=$env:SONAR_HOST_URL" `
                         "-Dsonar.login=$env:SONAR_TOKEN"