name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - sonarqube-automation
  pull_request:
    branches:
      - main
      - sonarqube-automation

jobs:
  sonarQube:
    runs-on: [self-hosted]

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "localhost:9000"
        run: |
          sonar-scanner "-Dsonar.projectKey=pingeso-p09" "-Dsonar.sources=." "-Dsonar.host.url=$SONAR_HOST_URL" "-Dsonar.login=$SONAR_TOKEN"
