name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - sonarqube-automation
      - code-quality-fixes
  pull_request:
    branches:
      - main
      - sonarqube-automation
      - code-quality-fixes

jobs:
  sonarQube:
    runs-on: [self-hosted]

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SQ Backend Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PROJECT }}
        run: |
          sonar-scanner -X

      - name: SQ Frontend Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PROJECT }}
        run: |
          sonar-scanner -X